# El array de Numpy
Esta estructua es el objeto principal de la librería Numpy, es en ella en la que surge la magia de tan poderosa herramienta.

Empezamos importando la libreria

In [1]:
import numpy as np

Creamos una lista normal de python

In [2]:
array = [1, 2, 3, 4, 5, 6, 7, 8, 9]
array

[1, 2, 3, 4, 5, 6, 7, 8, 9]

La lista "array" la transformamos a un Array de numpy

In [3]:
array = np.array(array)

Verificamos el tipo de dato de la variable "array"

In [4]:
type(array)

numpy.ndarray

## Accediendo a los datos de un array
Para acceder u obtener datos que se encuentren en un array lo hacemos mediante indices.
<br>
_Recordemos que en programación los indices empiezan a partir de la posición 0_

In [6]:
# Del array anterior
array


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# Accederemos al valor 5 que se encuentra en la posición 4
array[4]

5

In [14]:
# Sino conocemos la longitud del array y queremos acceder a su último elemento, lo podemos lograr de la siguiente manera
array[-1]

9

Mediante la técnica **Slicing** podemos acceder a 1 o más valores de un <code>array</code>, esto lo podemos lograr mediante los indices, aquí podemos utilizar el indice de inicio e indice final separados por dos puntos `:` algo así: <br>
<code>
array[indicie_inicio : indice_final]
</code>

In [9]:
# Los primeros 4 elementos del array
array[0:4]

array([1, 2, 3, 4])

In [10]:
# Sino le indicamos el indice de inicio por default toma el 0
array[:4]

array([1, 2, 3, 4])

Cabe mencionar que el indice `4` contiene el elemento con valor `5`, sin embargo python lo va a omitir y tomara el anterior, lo toma como:  `indice_final - 1` y nos da como resultado el indice 3, por eso toma hasta el elemento de dicha posición

In [12]:
# Omite el último elemento
array[:-1]

array([1, 2, 3, 4, 5, 6, 7, 8])

Junto con la técnica de **slicing** podemos aplicar saltos entre el array, y esto lo logramos con un 3er indice separado con dos puntos (`:`) de los dos indices anteriors, el ultimo indice le dice al array el número de saltos que debera hacer.
<br>
<code>
array[indice_inicio : indice_fina : numero_saltos]
</code>
<br>
**NOTA**: Si se omiten los dos primeros indices (`array[::salto]`) empezará desde la posición `0` hasta el final del array

In [15]:
# Empezando de la posición 2 hasta posición 7, daremos dos saltos
array[2:7:2]

array([3, 5, 7])

In [16]:
# Empezando desde la posición 0 a la última posición, daremos 3 saltos
array[::3]

array([1, 4, 7])

## Matrices
Una matriz es un array de 2 dimenciones, o lo ques lo mismo un array con n arrays en su interior. En este caso cada elemento del array principal es un array indemendiente. 
<br>
Al igual que en el ejemplo anterior, las matrices las creamos como listas y le aplicamos la funcionalidad array de la libreria numpy

In [17]:
matriz = [ [1, 2, 3], [4, 5, 6], [7, 8, 9] ]
matriz

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

Transformamos la matriz que acabamos de crear en un objeto array de numpy

In [18]:
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

En la matriz que creamos, podemos observar que es un arreglo (array) con 3 elementos, cada elemento es un array en si mismo. 

### Acceso a datos de una matriz
Al igual que en un array normal, o bien de una sola dimensión, en las matrices también podemos acceder a sus elementos mediante sus indices, en este caso la diferencia radica en que los elementos que obtendremos del array principal son otros arrays.

In [19]:
# Accediendo al elemento 0 de la matriz
matriz[0]

array([1, 2, 3])

Si bien lo que obtubimos fue un arreglo (`array([1, 2, 3])`), entonces ¿cómo podemos obtener los elementos contenidos en los arrays secundarios?, de igual forma, lo haremos mediante los indices, pero ahora sobre los indices del array secundario.
<br>
Para hacer mas sencilla la explicacion de como funcionan los indices en una matriz, lo podemos ver como una tabla, siendo los elementos del array principal las filas, y los elementos contenidos en los arrays secundarios las columnas, vemoslo en la siguiente tabla:

             Columnas (Elementos de cada array secundario)  
           | ------ |    
|indice| 0 | 1 | 2 |
|------|---|---|---|
| **0**| 1 | 2 | 3 |
| **1**| 4 | 5 | 6 |
| **2**| 7 | 8 | 9 |

Entonces si queremos obtener el elemento con valor `6`, necesitamos acceder a la fila `1` en la columna `2` (ambos son indices de a matriz), si bien al colocar `matriz[indice]` nos regresa un array (fila) podemos entenderlo como `matriz[indice_fila]`, enontces ¿cómo accedo al valor de una columna?, con el indice de la columna despues del indice de la fila separado por una coma `,` de la siguiente manera: `matriz[indice_fila, indice_columna]`. Veamoslo en practica

In [21]:
# Accederemos al elemento de la fila 1 en la columna 2
matriz[1,2]

6