# Creando arrays 
Una forma de crear arrays en Numpy es dandole como entrada una lista predefinida de Python, sin embargo esta libreria es mucho más versatil y nos permite crear arreglos a partir de un rango dado, haciendo nuestro trabajo más eficiente y sencillo.

In [1]:
import numpy as np

En Python podemos crear una lista a partir de un iterable con un rango dado.
<br>
En el siguiente ejemplo le decimos a la función `range` que nos genere un iterable de 10 elementos partiendo desde 0.

In [6]:
list(range(0, 10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

## arange

Numpy nos brinda una función similar llamada `arange` que también recibe como parametro el inicio y el total de elementos. A diferencia de `range` en Python es que con Numpy no necesitamos convertir a una lista ó arreglo el resultado de la función `arange`.

In [5]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Opcionalmente esta función recibe un tercer argumento llamado "step" o salto, el cual indica cuantos saltos dará entre elementos.
<br>
**Argumentos:**
- `start`: Valor donde va a iniciar el rango.
- `stop`: Punto donde terminará el rango.
- `step`: Saltos (pasos) que dará entre elementos.




In [7]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## zeros

Esta funcionalidad nos da la facilidad de crear arrays de **n** dimensiones donde todos sus valores son `0`.
<br>
Crear arreglos de `0`'s es sumamente útil cuando queremos preestablecer un esquema que utilizaremos más delante.

In [14]:
zero_array = np.zeros(5)
zero_array

array([0., 0., 0., 0., 0.])

Por default Numpy rellena de `0` el array pero en `0` de tipo `float64`, por esa razon aparece con un punto decimal a la derecha.

In [13]:
zero_array.dtype

dtype('float64')

La función `zeros` recibe obligatoriamente el argumento **shape** que indica la forma que va a tener el array (vector, matriz ó tensor).
<br>
En el ejemplo anterior se le envía un `5` y Numpy lo interpreta como un vector de tamaño 5 (cinco elementos).
<br> 
Pero si lo que necesitamos es crear una matriz de `0`'s, entonces le enviaremos una tupla con dos elementos, donde `tupla = (numero_filas, numero_columnas)`.


In [16]:
np.zeros((3,5)) # Matriz de 3 x 5 con valores en 0 de tipo floar64

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Para crear un tensor tendríamos que aumentar los elementos de la tupla segun las dimensiones que necesitemos.

In [17]:
np.zeros((2,3,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [19]:
np.zeros((2,3,5,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]]])

## ones

Es exactamente lo mismo que la función `zeros` con la diferencia que el array generado contiene solo elementos con valor `1` de tipo float64

In [20]:
np.ones(5) # Array de tipo vector con 5 elementos

array([1., 1., 1., 1., 1.])

In [22]:
np.ones((3, 5)) # Array de tipo matriz con 3 filas y 5 columnas

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
np.ones((2,3,5)) # Array de tipo tensor con 3 dimensiones

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [24]:
np.ones((2,3,5,2)) # Array de tipo tensor con 4 dimensiones

array([[[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]]])

## linspace

Esta función genera un array n elementos con valores que se encuentren dentro de un determinado rango de valores que se envían como parametros. `linspace` recibe 3 parametros principales:
- `start`: Valor de inicio del rango
- `stop`: Valor final del rango
- `num`: Cantidad de elementos que contendrá el array, por default Numpy asigna 50 elementos si el argumento `num` no se envía

In [33]:
lin_array = np.linspace(0, 10)
lin_array

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [34]:
len(lin_array)

50

In [36]:
lin_array_2 = np.linspace(0, 20, 100)
lin_array_2

array([ 0.        ,  0.2020202 ,  0.4040404 ,  0.60606061,  0.80808081,
        1.01010101,  1.21212121,  1.41414141,  1.61616162,  1.81818182,
        2.02020202,  2.22222222,  2.42424242,  2.62626263,  2.82828283,
        3.03030303,  3.23232323,  3.43434343,  3.63636364,  3.83838384,
        4.04040404,  4.24242424,  4.44444444,  4.64646465,  4.84848485,
        5.05050505,  5.25252525,  5.45454545,  5.65656566,  5.85858586,
        6.06060606,  6.26262626,  6.46464646,  6.66666667,  6.86868687,
        7.07070707,  7.27272727,  7.47474747,  7.67676768,  7.87878788,
        8.08080808,  8.28282828,  8.48484848,  8.68686869,  8.88888889,
        9.09090909,  9.29292929,  9.49494949,  9.6969697 ,  9.8989899 ,
       10.1010101 , 10.3030303 , 10.50505051, 10.70707071, 10.90909091,
       11.11111111, 11.31313131, 11.51515152, 11.71717172, 11.91919192,
       12.12121212, 12.32323232, 12.52525253, 12.72727273, 12.92929293,
       13.13131313, 13.33333333, 13.53535354, 13.73737374, 13.93

In [37]:
len(lin_array_2)

100

## random

Cuando queremos trabajar con número aleatorios en Python necesitamos importar la libreria `random`, pero Numpy ya tiene integrada esa funcionalidad.

### rand
Genera un número aleatorio entre 0 y 1

In [38]:
np.random.rand()

0.3471794017820685

Por default no recibe ningun parametro y retora un solo valor aleatorio. Sin embargo si le mandamos un valor numérico como parametro, va a generar un array de números aleatorios del tamaño al que corresponde el valor envíado.

In [40]:
np.random.rand(5) # Genera un array de 5 números aleatorios

array([0.05281145, 0.84894306, 0.32674687, 0.55309424, 0.6793612 ])

Si a la función `rand` le mandamos 2 valores numéricos como argumentos va a crear una matriz.

In [47]:
np.random.rand(5,5) # Genera una matriz de 5 filas y 5 columnas con números aleatorios entre 0 y 1

array([[0.02606652, 0.47799499, 0.37397633, 0.68210667, 0.70367882],
       [0.73998958, 0.80998792, 0.10287799, 0.83793779, 0.47231464],
       [0.15572412, 0.88743281, 0.58704437, 0.03938166, 0.81688379],
       [0.33557404, 0.34152488, 0.78962038, 0.29472048, 0.01408456],
       [0.75429852, 0.56550726, 0.31689306, 0.98274288, 0.64588462]])

A `rand` puere recibir n argumentos numéricos, la cantidad de ellos definira el número de dimensiones

In [56]:
rand_n_array = np.random.rand(2, 5, 5)
rand_n_array

array([[[0.46273884, 0.40173995, 0.60728838, 0.2757073 , 0.91122417],
        [0.02247842, 0.19225305, 0.27839918, 0.84734014, 0.66792304],
        [0.67204471, 0.06145142, 0.8911092 , 0.62574665, 0.25075558],
        [0.29322371, 0.93362759, 0.22025249, 0.96493128, 0.17376339],
        [0.16784011, 0.52536256, 0.23799095, 0.90122539, 0.61743411]],

       [[0.53659634, 0.9664346 , 0.11667961, 0.24189865, 0.30439509],
        [0.60346425, 0.56275992, 0.61108899, 0.56963321, 0.51999633],
        [0.22802563, 0.39898052, 0.86834493, 0.7856789 , 0.91430006],
        [0.30133759, 0.77523123, 0.97352356, 0.32663162, 0.06284141],
        [0.77722935, 0.200282  , 0.011483  , 0.04005667, 0.50772116]]])

In [55]:
rand_n_array.ndim

3

In [60]:
rand_n_array2 = np.random.rand(2, 3, 1, 2)
rand_n_array2

array([[[[0.22585546, 0.34527524]],

        [[0.84489741, 0.45590146]],

        [[0.44242857, 0.3465361 ]]],


       [[[0.4706563 , 0.99064032]],

        [[0.2979513 , 0.26805804]],

        [[0.25327959, 0.11921986]]]])

In [59]:
rand_n_array2.ndim

4

### randint
Genera un número aleatorio entero que este dentro de un rango dado. A diferencia de `rand` esta función requiere que se le manden obligatoriamente los primeros dos parametros
- `low`: Valor aleatorio mínimo.
- `high`: Valor aleatorio máximo.


In [70]:
np.random.randint(1, 10)

8

Opcionalmente recibe un tercer argumento el cual define la forma (`shape`)
- `drawn`: Define la forma del array, si se envia un valor `int` entonces regresará un vector de tamnaño **n** (valor enviado). Si se le envía una tupla con **n** "elementos" se creará un array de dimensión **n**

In [71]:
np.random.randint(1, 10, 8) # Genera un vector de 8 elementos con valores entre 1 y 10 

array([8, 6, 5, 5, 3, 8, 9, 7])

In [66]:
np.random.randint(1, 10, (3,4)) # # Genera una matriz de 3 filas y 4 columnas con valores entre 1 y 10 

array([[3, 4, 8, 3],
       [7, 6, 4, 4],
       [5, 3, 1, 5]])

In [68]:
np.random.randint(1, 10, (3, 2, 4))

array([[[8, 8, 9, 6],
        [6, 4, 3, 7]],

       [[8, 3, 3, 4],
        [8, 4, 4, 4]],

       [[3, 8, 1, 8],
        [9, 7, 5, 5]]])

[Documentación oficial](https://numpy.org/doc/stable/reference/routines.array-creation.html)