# Operaciones
Operaciones básicas de arrays

Numpy ofrece la posibilidad de ralizar operaciones aritmeticas, algebraicas, etc., directamente en sus arrays sin recorrer cada uno de sus elementos para efectuar la operación.

Operacion aritmetica en una lista de python

In [1]:
lista = [1,2,3]
lista * 2

[1, 2, 3, 1, 2, 3]

En `lista * 2` Python interpretó que lo que queremos hacer es duplicar la lista no multiplicar sus elementos por 2, para aplicar esa multiplicación a sus elementos necesitamos recorrerlo.

In [2]:
nueva_lista = []
for elemento in lista:
    nueva_lista.append(elemento * 2)

nueva_lista

[2, 4, 6]

Recorrer la lista funciona, sin embargo la solución es ineficiente cuando trabajamos con set de datos mucho más grandes, es ahí donde entran las bondades de los arrays de Numpy.

In [3]:
import numpy as np

In [4]:
array = np.arange(0, 10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
array * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

El array de Numpy interpretó la operación `array * 2` como la multiplicación de cada elemento por 2, así como aplicamos la multiplicación podemos aplicar más operaciones.

In [6]:
array + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
array / 5

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8])

In [8]:
1 / array

/tmp/ipykernel_1253/1508088032.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / array


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

La división entre `0` no es matemáticamente posible, y Numpy nos los dice, pero no detiene la ejecución sino que en el indice donde estaba el elemento 0 nos coloca `inf`

Operaciones entre dos arrays

In [9]:
array2 = array.copy()
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
array * array2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [11]:
array / array2

/tmp/ipykernel_1253/3634090195.py:1: RuntimeWarning: invalid value encountered in true_divide
  array / array2


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

Operaciones con matricies

In [13]:
matriz = array.reshape(2, 5)
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [14]:
matriz * 2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [15]:
matriz ** 2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

Operaciones con 2 matrices

In [16]:
matriz2 = matriz.copy()
matriz2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [17]:
matriz - matriz2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [18]:
matriz * matriz2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

Operación de [producto punto](https://es.wikipedia.org/wiki/Producto_escalar) entre matrices

In [19]:
np.matmul(matriz, matriz2)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 5)

La solución al error como lo dice la definición del producto punto es transponer una de las matrices.

In [20]:
np.matmul(matriz, matriz2.T)

array([[ 30,  80],
       [ 80, 255]])

Otra forma de apliciar el producto punto

In [22]:
matriz2 @ matriz.T

array([[ 30,  80],
       [ 80, 255]])