# Funciones principales
Lista y ejemplos de las funciones principales o más utilizadas de Numpy en Data Science.

Los ejemplos los realizaremos con las estructuras de tipo vector y matricial.

In [1]:
import numpy as np

In [3]:
array = np.random.randint(0, 50, 30)
array

array([21,  0, 19, 37, 13, 41,  9, 35, 15,  2, 47,  2, 10,  0,  9, 12, 10,
       35, 37, 28,  7, 22, 42, 20, 27,  1, 22,  3, 18, 10])

In [5]:
matriz = array.reshape((5, 6))
matriz

array([[21,  0, 19, 37, 13, 41],
       [ 9, 35, 15,  2, 47,  2],
       [10,  0,  9, 12, 10, 35],
       [37, 28,  7, 22, 42, 20],
       [27,  1, 22,  3, 18, 10]])

## max

La función `max` nos va a regresar el valor maximo que se encuentra en una estructura.

In [6]:
array.max()

47

In [24]:
matriz.max() # Maximo general

47

En el caso de la estructura matricial, podemos indicarle el eje de busqueda del valor máximo, este eje puede ser por columnas o filas
- `eje 0`: Columnas
- `eje 1`: Filas
Al indicarle el eje de busqueda la función nos regresara un array con la lista de aquellos valores maximos que encontró en el eje indicado.

In [25]:
matriz # visualizar estructura

array([[21,  0, 19, 37, 13, 41],
       [ 9, 35, 15,  2, 47,  2],
       [10,  0,  9, 12, 10, 35],
       [37, 28,  7, 22, 42, 20],
       [27,  1, 22,  3, 18, 10]])

In [26]:
# Maximo por columnas
matriz.max(0)

array([37, 35, 22, 37, 47, 41])

In [27]:
# Maximo por filas
matriz.max(1)

array([41, 47, 35, 42, 27])

## argmax

Regresa el indice de la estructura donde se encuentra el valor máximo

In [28]:
# visualizar estructura
array

array([21,  0, 19, 37, 13, 41,  9, 35, 15,  2, 47,  2, 10,  0,  9, 12, 10,
       35, 37, 28,  7, 22, 42, 20, 27,  1, 22,  3, 18, 10])

In [29]:
array.argmax()

10

Con la matriz funciona igual sino le pasamos ningun parametro a la función `argmax` pero al igual que `max` esta función opcionalmente también recibe el parametro del eje.

In [30]:
# visualizar estructura
matriz

array([[21,  0, 19, 37, 13, 41],
       [ 9, 35, 15,  2, 47,  2],
       [10,  0,  9, 12, 10, 35],
       [37, 28,  7, 22, 42, 20],
       [27,  1, 22,  3, 18, 10]])

In [14]:
matriz.argmax() # Indice del valor máximo general

10

In [17]:
matriz.argmax(0) # Indices de los valors maximos en cada columna

array([3, 1, 4, 0, 1, 0])

In [18]:
matriz.argmax(1) # Indices de los valors maximos en cada fila

array([5, 4, 5, 4, 0])

## min

Es la contraparte de `max` y esque esta función devuelve los valores más pequeños de una estructura.

In [20]:
# Visualizar estructura
array

array([21,  0, 19, 37, 13, 41,  9, 35, 15,  2, 47,  2, 10,  0,  9, 12, 10,
       35, 37, 28,  7, 22, 42, 20, 27,  1, 22,  3, 18, 10])

In [21]:
array.min()

0

Con `min` también podemos indicarle de manera opcional el eje de busqueda del valor mínimo.

In [31]:
# Visualizar estructura
matriz

array([[21,  0, 19, 37, 13, 41],
       [ 9, 35, 15,  2, 47,  2],
       [10,  0,  9, 12, 10, 35],
       [37, 28,  7, 22, 42, 20],
       [27,  1, 22,  3, 18, 10]])

In [22]:
matriz.min() # minimo general

0

In [23]:
matriz.min(0) # minimo por columnas

array([ 9,  0,  7,  2, 10,  2])

In [32]:
matriz.min(1) # minimo por filas

array([0, 2, 0, 7, 1])

## argmin

Regresa el indice del valor mínimo de una estructura, en el caso de una matriz recibe opcionalmente el parametro del eje.


In [37]:
# visualizar estructura
array

array([21,  0, 19, 37, 13, 41,  9, 35, 15,  2, 47,  2, 10,  0,  9, 12, 10,
       35, 37, 28,  7, 22, 42, 20, 27,  1, 22,  3, 18, 10])

In [38]:
# visualizar estructura
matriz

array([[21,  0, 19, 37, 13, 41],
       [ 9, 35, 15,  2, 47,  2],
       [10,  0,  9, 12, 10, 35],
       [37, 28,  7, 22, 42, 20],
       [27,  1, 22,  3, 18, 10]])

In [33]:
array.argmin()

1

In [34]:
matriz.argmin() # Busqueda del indice del valor mimino general

1

In [35]:
matriz.argmin(0) # Busqueda del indice del valor mimino por columnas

array([1, 0, 3, 1, 2, 1])

In [39]:
matriz.argmin(1) # Busqueda del indice del valor mimino por filas

array([1, 3, 1, 2, 1])

## ptp
Peak to Peak, calcula la diferencia (o distancia) entre el valor máximo y mímino de una estructur, en el caso de una matriz recibe opcionalmente el parametro del eje.

In [41]:
array

array([21,  0, 19, 37, 13, 41,  9, 35, 15,  2, 47,  2, 10,  0,  9, 12, 10,
       35, 37, 28,  7, 22, 42, 20, 27,  1, 22,  3, 18, 10])

In [42]:
array.ptp()

47

In [44]:
array.max() - array.min() # Just for fun

47

In [45]:
# visualizar estructura
matriz

array([[21,  0, 19, 37, 13, 41],
       [ 9, 35, 15,  2, 47,  2],
       [10,  0,  9, 12, 10, 35],
       [37, 28,  7, 22, 42, 20],
       [27,  1, 22,  3, 18, 10]])

In [46]:
matriz.ptp() # Diferencia general

47

In [47]:
matriz.ptp(0) # Diferencia por  columnas

array([28, 35, 15, 35, 37, 39])

In [48]:
matriz.ptp(1) # Diferencia por filas

array([41, 45, 35, 35, 26])

## percentile

Calcula el percentil de un grupo de datos. Esta función recive varios parametros, los principales son:
- `array`: Puede ser un vector, matriz o tensor y es nuestro grupo de datos.
- `q`: Es el percentil y pueden ser valores entre 0 y 100, donde 0 nos regresa el valor mínimo y 100 el valor máximo, pero si le enviamos 50 nos regresa la media del set de datos. Es parametro también puede ser una secuencia de números entre 0 y 100, se calculara el percentil por cada valor incluido en la secuencia.


In [53]:
# visualizar estructura ordenada
array.sort()
array

array([ 0,  0,  1,  2,  2,  3,  7,  9,  9, 10, 10, 10, 12, 13, 15, 18, 19,
       20, 21, 22, 22, 27, 28, 35, 35, 37, 37, 41, 42, 47])

In [49]:
np.percentile(array, 0) # El valor minimo del array

0.0

In [50]:
np.percentile(array, 100) # Valor maximo del array

47.0

In [51]:
np.percentile(array, 50) # mediana del array

16.5

Si la estrucutra es una matriz opcionalmente podemos indicarle el eje donde realizará el cálculo

In [55]:
# visialzar estructura ordenada
matriz.sort()
matriz

array([[ 0,  0,  1,  2,  2,  3],
       [ 7,  9,  9, 10, 10, 10],
       [12, 13, 15, 18, 19, 20],
       [21, 22, 22, 27, 28, 35],
       [35, 37, 37, 41, 42, 47]])

In [56]:
np.percentile(matriz, 0)# El valor minimo de la matriz

0.0

In [57]:
np.percentile(matriz, 100)# El valor maximo de la matriz

47.0

In [60]:
np.percentile(matriz, 50)# La mediana de la matriz

16.5

In [61]:
np.percentile(matriz, 50, 0)# La mediana de la matriz por columna

array([12., 13., 15., 18., 19., 20.])

In [62]:
np.percentile(matriz, 50, 1)# La mediana de la matriz por fila

array([ 1.5,  9.5, 16.5, 24.5, 39. ])

In [64]:
np.percentile(matriz, [0, 50, 100]) # Obtenemos el minimo, la mediana y el maximo de la matriz en general

array([ 0. , 16.5, 47. ])

In [65]:
np.percentile(matriz, [0, 50, 100], 0) # Obtenemos el minimo, la mediana y el maximo por columna

array([[ 0.,  0.,  1.,  2.,  2.,  3.],
       [12., 13., 15., 18., 19., 20.],
       [35., 37., 37., 41., 42., 47.]])

## mean

Calcula la media (o promedio) de un set de datos contenidos en una estructura, para las matrices opcionalmente podemos enviar el eje.
<br>
El calculo de la media es la suma de todos los elementos dividito entre el número total de dichos elementos
<br>
<br>

$\text{\={X}}={\frac 1 n} {\sum_{i=1}^n}{x_i}$
<br>
<br>
o bien
<br>
<br>
$\text{\={X}}={\frac 1 n} {\sum_{i=1}^n}{x_i} = {\frac {x_{1} + x_{2} + ... +x_{n}} n }$

In [82]:
# visualizar estructura
array

array([ 0,  0,  1,  2,  2,  3,  7,  9,  9, 10, 10, 10, 12, 13, 15, 18, 19,
       20, 21, 22, 22, 27, 28, 35, 35, 37, 37, 41, 42, 47])

In [83]:
np.mean(array)

18.466666666666665

In [84]:
np.mean(matriz) # media general de la matriz

18.466666666666665

In [85]:
np.mean(matriz, 0) # media por columna

array([15. , 16.2, 16.8, 19.6, 20.2, 23. ])

In [86]:
np.mean(matriz, 1) # media por fila

array([ 1.33333333,  9.16666667, 16.16666667, 25.83333333, 39.83333333])

## median

Calcula la mediana de una estructura, en el caso de una matriz recibe opcionalmente el parametro del eje.

In [66]:
# visualizar estructura
array

array([ 0,  0,  1,  2,  2,  3,  7,  9,  9, 10, 10, 10, 12, 13, 15, 18, 19,
       20, 21, 22, 22, 27, 28, 35, 35, 37, 37, 41, 42, 47])

In [67]:
np.median(array)

16.5

In [69]:
# vizualizar estructura
matriz

array([[ 0,  0,  1,  2,  2,  3],
       [ 7,  9,  9, 10, 10, 10],
       [12, 13, 15, 18, 19, 20],
       [21, 22, 22, 27, 28, 35],
       [35, 37, 37, 41, 42, 47]])

In [70]:
np.median(matriz) # mediana general de la matriz

16.5

In [71]:
np.median(matriz, 0) # mediana por coluna

array([12., 13., 15., 18., 19., 20.])

In [72]:
np.median(matriz, 1) # mediana por fila

array([ 1.5,  9.5, 16.5, 24.5, 39. ])

## std

Calcula la desviasión estandar de una estructura, si trabajamos con matrices podemos indicarle el eje.
<br>
<br>
$\sigma = \sqrt{{\frac 1n} {\sum_{i=1}^n}(x_i - \text{\=X})^2}$

In [73]:
np.std(array)

13.766464889562446

In [74]:
np.std(matriz) # desviasion estandar general de la matriz

13.766464889562446

In [75]:
np.std(matriz, 0) # desviasion estandar por columna

array([12.11610498, 12.57616794, 12.23764683, 13.54400236, 13.94847662,
       16.11210725])

In [77]:
np.std(matriz, 1) # desviasion estandar por fila

array([1.1055416 , 1.06718737, 3.02305952, 4.87909372, 4.0173236 ])

## var

Calcula la varianza de una estructura, si trabajamos con matrices podemos indicarle el eje.
<br>
<br>
$Var(X) ={\frac 1n}{\sum_{i=1}^n} (x_i -\text{\=X})^2$
<br>
<br>
Si aplicamos la raíz cuadrada a la vaianza obtendremos la desviación estandar

In [79]:
# visualizar estructura
array

array([ 0,  0,  1,  2,  2,  3,  7,  9,  9, 10, 10, 10, 12, 13, 15, 18, 19,
       20, 21, 22, 22, 27, 28, 35, 35, 37, 37, 41, 42, 47])

In [80]:
np.var(array)

189.51555555555555

In [81]:
np.var(array) ** 0.5

13.766464889562446

## concatenate

Esta función como su nombre lo indica, concatena dos o más arrays de la misma dimensión.
<br>

`concatenate` recibe como parametro una tupla con los arrays a concatenar, opcionalmente podemos especificar el eje (o axis).

In [106]:
a = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])

Si intentamos concatenar los arrays `a` y `b` obtendremos un error de tipo `ValueError`

In [91]:
np.concatenate((a, b), axis=0) # Concatena a y b en el eje 0 (columnas)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Corroboramos las dimensiones de los arrays

In [92]:
print(f'dimensión de a: {a.ndim}')
print(f'dimensión de b: {b.ndim}')

dimensión de a: 2
dimensión de b: 1


Al ser a de 2 dimensiones y b de 1 obtenemos el error anterior, para solucionarlo podemos aumentar las dimensiones del array b con la función `expand_dims`.

In [108]:
# expandiremos la dimensión b
b = np.expand_dims(b, axis=0) # dejamos una sola fila con dos columnas igual que la forma del array a
b.ndim

2

Con ambos arrays en 2 dimensiones ahora si podemos concatenarlos

In [110]:
c = np.concatenate((a,b), axis=0) # Concatena por columnas
c

array([[1, 2],
       [3, 4],
       [5, 6]])

La concatenación por columnas funcionó sin embargo si intentamos hacerlo por filas obtendremos un error tipo `ValueError`

In [111]:
d = np.concatenate((a,b), axis=1) 

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

El arror anterior ocurre porque los arrays no tienen la misma forma

In [112]:
print(f'a: {a.shape}')
print(f'b: {b.shape}')

a: (2, 2)
b: (1, 2)


Entonces para poder concatenar por filas, necesitamos transformar a b  con `shape` a la forma de a o bien utilizar la transpuesta de los arrays (convertir filas a columnas y columnas a filas, en sql lo conocemos como pivot).

In [113]:
d = np.concatenate((a,b.T), axis=1) # T es la transpuesta
d

array([[1, 2, 5],
       [3, 4, 6]])

---

## copy

copy a diferencia de las funciones anteriores no es una función matemática o estadistica, es más bien de ulitidad.
<br>
Tanto si trabajamos con listas de Python o arrays de Numpy nos vemos en la necesitad de copiar nuestras estructuras en otras variables, normalmente lo hacemos de la siguiente manera:

In [116]:
my_array = np.array([1,2,3,4,5])
my_array

array([1, 2, 3, 4, 5])

In [121]:
copia = my_array
copia

array([0, 0, 3, 4, 5])

En cada uno de los metodos anteriores lo que enrealidad estamos haciendo es pasar una referencia en memoria, lo cual significa que si modificamos la copia también modificamos el original.

In [122]:
copia[:2] = 100
print(f'copia: {copia}')
print(f'my_array: {my_array}')

copia: [100 100   3   4   5]
my_array: [100 100   3   4   5]


En estos escenarios es donde `copy` nos ayuda a mantener intactos los datos del array original creando un array nuevo a partir de del array original.

In [124]:
otra_copia = my_array.copy()
otra_copia

array([100, 100,   3,   4,   5])

In [125]:
otra_copia[:] = 5 # Asignamos el valor 5 a todos los elementos del array
print(f'otra_copia: {otra_copia}')
print(f'my_array: {my_array}')

otra_copia: [5 5 5 5 5]
my_array: [100 100   3   4   5]


---

[Documentación de funciones matemáticas](https://numpy.org/doc/stable/reference/routines.math.html)
<br>
[Documentación de funciones estadisticas](https://numpy.org/doc/stable/reference/routines.statistics.html)