# Shape y Reshape

- **Shape**: Forma que tiene un arreglo. Nos dice si la estructura del arreglo es Scalar, Vectoria, Matriz ó Tensor.
- **Reshape**: Cambia la forma del arreglo

In [1]:
import numpy as np

Creamos un arreglo matricial de 3 filas y 2 columnas con números aleatorios entre 0 y 10 

In [18]:
array = np.random.randint(0, 10, (3, 2))
array

array([[2, 6],
       [4, 8],
       [4, 2]])

In [19]:
array.shape

(3, 2)

La propiedad `shape` del array nos regresa la tupla `(3, 2)` con la cual lo definimos en un inicio, y es esa tupla la que indica la forma de nuestro array

`reshape` es una función perteneciente a los arreglos de Numpy y nos permite modificar la forma original de un array.

In [20]:
array = array.reshape(1,6)
array

array([[2, 6, 4, 8, 4, 2]])

In [15]:
array.shape

(1, 6)

In [28]:
array = array.reshape(2, 3)
array

array([[2, 6, 4],
       [8, 4, 2]])

Otra forma de aplicar un cambio de forma a un array es directamente de la instancia de Numpy con la función `resape` 

In [30]:
array = np.reshape(array, (6,1))
array

array([[2],
       [6],
       [4],
       [8],
       [4],
       [2]])

**NOTA**: Solo es posible cambiar la forma de un array cuando aquella nueva forma que estemos aplicando sea soportada por el array. 
<br>
En el array original teniamos una matriz de 3 x 2 con 6 datos, si intentamos modificarlo a un array con menos o con mas elementos obtendremos un error de tipo `ValueError`

In [26]:
np.reshape(array, (6,6))

ValueError: cannot reshape array of size 6 into shape (6,6)

Al hacer un `reshape` a un array Numpy por default los ordena de forma líneal, un row tras de otro.
<br>
Tomemos como referencia el array en su forma original de 3 x 2  

In [32]:
array = array.reshape(3,2)
array

array([[2, 6],
       [4, 8],
       [4, 2]])

Originalmente tenemos 3 rows, donde row 1 tiene [2, 6], row 2 tiene [4, 8] y el row 3 tiene [4, 2] si dejamos un solo row con 6 elementos entonces quedarian todos juntos empezando en 2 y terminando en el último 2

In [36]:
array = np.reshape(array, (1,6))
array

array([[2, 6, 4, 8, 4, 2]])

Si ese mismo array lo cambiamos a una matriz de 2 filas con 3 columnas, entonces Numpy por default tomara los datos de 3 en 3 y los colocara en sus respectivas filas.

In [37]:
array = np.reshape(array, (2, 3))
array

array([[2, 6, 4],
       [8, 4, 2]])

Una ventaja de hacer reshape con Numpy es que le podemos indicar el tipo de ordenamiento.

In [38]:
# Ordenamiento como el lenguaje C
array = np.reshape(array, (3, 2), 'C')
array

array([[2, 6],
       [4, 8],
       [4, 2]])

In [43]:
# Ordenamiento como el lenguaje fortran, En este caso el ordenamiento lo hace por columnas
array = np.reshape(array, (2, 3), 'F')
array

array([[2, 4, 8],
       [4, 6, 2]])

In [44]:
# Ordenamiento optimizado segun el ordenador donde ejecutemos nuestro programa
array = np.reshape(array, (2, 3), 'A')
array

array([[2, 4, 8],
       [4, 6, 2]])

Utilizar el ordenamiento optimizado tiene la dfesventaja de que no sabremos como Numpy va a ordenar los datos de nuestro array, podemos establecer el ordenamiento que más nos convenga y aplicarlo con el fin de conocer como quedaran nuestros datos despues de ser ordenados con reshape.