# Condiciones

Cuando necesitamos obtener datos de un array y el uso de slicing se queda corto es donde entran las condiciones.
<br>
Las condiciones nos ayudan a tomar datos especificos de un arreglo, por ejemplo obtener solo números pares, primos, mayores a o menores a, etc. 

In [1]:
import numpy as np

In [6]:
array = np.linspace(0, 100, 20, dtype='int16')
array

array([  0,   5,  10,  15,  21,  26,  31,  36,  42,  47,  52,  57,  63,
        68,  73,  78,  84,  89,  94, 100], dtype=int16)

Si al array le aplicamos un condicional para saber que elementos son mayores a 20 obtendremos un array te tipo bool que nos indica que elementos cumplen o no con la condición.

In [10]:
array > 20

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

El resultado de la condición es un array booleano, pero y si quiero obteler el valor el los elementos?, entonces le damos esa condición al array

In [11]:
cond = array > 20
array[cond]

array([ 21,  26,  31,  36,  42,  47,  52,  57,  63,  68,  73,  78,  84,
        89,  94, 100], dtype=int16)

O bien

In [13]:
array[array > 20]

array([ 21,  26,  31,  36,  42,  47,  52,  57,  63,  68,  73,  78,  84,
        89,  94, 100], dtype=int16)

Aumentando la complejidad de la condición

In [14]:
# valores mayores a 20 y menores a 50
array[(array > 20) & array < 50]

array([  0,   5,  10,  15,  21,  26,  31,  36,  42,  47,  52,  57,  63,
        68,  73,  78,  84,  89,  94, 100], dtype=int16)

Solo los pares

In [15]:
array[array % 2 == 0]

array([  0,  10,  26,  36,  42,  52,  68,  78,  84,  94, 100], dtype=int16)

Las condiciones ademas de regresar los elementos que la cumplan, también podemos modificar esos elementos (igual que con slicing).

In [18]:
array[array % 5 == 0] = 777
array

array([777, 777, 777, 777,  21,  26,  31,  36,  42,  47,  52,  57,  63,
        68,  73,  78,  84,  89,  94, 777], dtype=int16)