# Tipos de datos con Numpy
Los tipos de datos que Numpy proporciona se aplican a cada elemento del array con el que estemos trabajando, como bien sabemos en Python podemos tener una lista con varios tipos de datos en él, sin embargo, la librería Numpy solo permite que un tipo de dato en el array que creemos con `np.array([...])`

Entre los tipos de dato que Numpy provee encontramos los siguientes:

In [1]:
import numpy as np

In [14]:
lista = [1,2,3,4,5]

### int64

In [15]:
array = np.array(lista)
array.dtype

dtype('int64')

In [16]:
array

array([1, 2, 3, 4, 5])

La propiedad `dtype` nos dice cual es el tipo de dato que contiene un array de numpy

### float64

In [17]:
arrayF = np.array(lista, dtype='float64')
arrayF.dtype

dtype('float64')

In [18]:
arrayF

array([1., 2., 3., 4., 5.])

La expresión `np.array(lista, dtype='float64')` indica que al crear el array sus elementos seran de tipp `floar64`, pero ¿qué pasa si el array ya fue creado con un tipo de dato distinto al que necesitamos? 
<br>
Numpy nos da la función `astype` para cambiarle el tipo de dato a un array.

In [21]:
arrayF2 = np.array(lista) # por default es una array int64
arrayF2.dtype

dtype('int64')

In [24]:
arrayF2 = arrayF2.astype(np.float64)
arrayF2

array([1., 2., 3., 4., 5.])

In [25]:
arrayF2.dtype

dtype('float64')

### bool_
Al transformar cualquier tipo numérico a booleano Python y Numpy interpretan el 0 como False y cualquier otro número como True

In [29]:
arrayB = np.array([0, 1, 2, 3, 4, 5])
arrayB = arrayB.astype(np.bool_)
arrayB

array([False,  True,  True,  True,  True,  True])

In [27]:
arrayB.dtype

dtype('bool')

### string_
Transforma los valores numéricos a caracteres de tipo texto.

In [30]:
arrayS = np.array([0, 1, 2, 3, 4, 5])
arrayS = arrayS.astype(np.string_)
arrayS

array([b'0', b'1', b'2', b'3', b'4', b'5'], dtype='|S21')

Si por el contrario iniciamos con un array de tipo string e intentamos transformarlo a otro tipo de dato Numpy lo convierte a ese tipo

In [33]:
arrayS2 = np.array(['0', '1', '2', '3', '4', '5'])
arrayS2 = arrayS2.astype(np.bool_)
arrayS2

array([False,  True,  True,  True,  True,  True])

Sin embargo, cuando el array de tipo string contiene un elemento con caracteres distintos a números la conversión marcara un error de tipo `ValueError`

In [32]:
arrayS3 = np.array(['hola', '1', '2', '3', '4', '5'])
arrayS3 = arrayS3.astype(np.bool_)
arrayS3

ValueError: invalid literal for int() with base 10: 'hola'

[Más tipos de datos en la documentación oficial de Numpy](https://numpy.org/doc/stable/user/basics.types.html)