# Dimensiones
La librería Numpy es bastante poderosa con el manejo de datos en formato (estructura) de array, nos permite trabajar con datos en distintas dimensiones.

In [1]:
import numpy as np

## Scalar
Es de dimensión `0`, no esta dentro de una estructura, es un dato en si mismo.

In [5]:
scalar = np.array(31)
print(f' dimensión: {scalar.ndim}, valor: {scalar}')

 dimensión: 0, valor: 31


La propiedad `ndim` de un array nos regresa el número de dimensiones.

## Vector
Es de dimensión `1`, en Python lo conocemos como `lista` y se puede representar de la siguiente manera:
<br>
| 0 | 1 | 2 | 3 | 4 |
|---|---|---|---|---|

In [7]:
lista_vector = [1, 2, 3, 4]
vector = np.array(lista_vector)
print(f'dimesion: {vector.ndim}, valor: {vector}')

dimesion: 1, valor: [1 2 3 4]


## Matriz
Es de dimesión `2`, lo podemos representar como una tabla con filas y columnas, donde las filas son los datos/ejemplos y las columnas sus características (como una hoja de calculo de Excel).
<br>
Lo podemos ver de la siguiente manera:
<br>
| Color | País | Edad |
|-------|------|------|
| Rojo | México | 31 |
| Verde | Canada | 20 |

In [10]:
lista_matriz = [[1,2,3], [4,5,6]]
matriz = np.array(lista_matriz)
print(f'dimesión: {matriz.ndim}') 
print(f'valor: {matriz}')

dimesión: 2
valor: [[1 2 3]
 [4 5 6]]


## Tensor
Es de dimensión `n`, usualmente se manejan en series de tiempo (3 dimesiones), donde se tiene datos/ejemplos, sus características y su comportamiento a travez del tiempo (esto en almacences de datos se le conoce como cubos de datos).

In [15]:
lista_tensor = [ [ [1,2,3], [4,5,6] ], [ [7,8,9], [10, 11, 12] ] ]
tensor = np.array(lista_tensor)
print(f'dimensión: {tensor.ndim}')
print(f'valor: {tensor}')

dimensión: 3
valor: [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## Agregar o eliminar dimensiones

Podemos crear un array con una dimensión definida desde el inicio:

In [16]:
# Createmos un tensor de dimensián 0
tensor_10 = np.array([1,2,3], ndmin=10)
print(f'dimensión: {tensor_10.ndim}')
print(tensor_10)

dimensión: 10
[[[[[[[[[[1 2 3]]]]]]]]]]


Si el array fue creado con una cantidad de dimensiones menor a la que necesitamos, podemos expandir sus dimenciones

In [23]:
expand = np.array([1,2,3])
print(expand.ndim)
expand = np.expand_dims(expand, axis=0)
# axis=0 -> Nivel de filas
# axis=1 -> Nivel de columnas, combierte cada elemento del array en otro array
print(expand.ndim)
print(expand)

1
2
[[1 2 3]]


Si el array tiene dimensiones que no se utilizan podemos eliminarlas

In [28]:
sqeez = np.array([1,2,3], ndmin=10)
print(f'dimensión: {sqeez.ndim}')
print(sqeez)
sqeez = sqeez.squeeze()
print(f'dimension: {sqeez.ndim}')
print(sqeez)


dimensión: 10
[[[[[[[[[[1 2 3]]]]]]]]]]
dimension: 1
[1 2 3]
