# Shape y Reshape

- **Shape**: Forma que tiene un arreglo. Nos dice si la estructura del arreglo es Scalar, Vectoria, Matriz ó Tensor.
- **Reshape**: Cambia la forma del arreglo

In [2]:
import numpy as np

Creamos un arreglo matricial de 3 filas y 2 columnas con números aleatorios entre 0 y 10 

In [3]:
array = np.random.randint(0, 10, (3, 2))
array

array([[6, 4],
       [9, 7],
       [9, 6]])

In [4]:
array.shape

(3, 2)

La propiedad `shape` del array nos regresa la tupla `(3, 2)` con la cual lo definimos en un inicio, y es esa tupla la que indica la forma de nuestro array

`reshape` es una función perteneciente a los arreglos de Numpy y nos permite modificar la forma original de un array.

In [5]:
array = array.reshape(1,6)
array

array([[6, 4, 9, 7, 9, 6]])

In [6]:
array.shape

(1, 6)

In [7]:
array = array.reshape(2, 3)
array

array([[6, 4, 9],
       [7, 9, 6]])

Otra forma de aplicar un cambio de forma a un array es directamente de la instancia de Numpy con la función `resape` 

In [8]:
array = np.reshape(array, (6,1))
array

array([[6],
       [4],
       [9],
       [7],
       [9],
       [6]])

**NOTA**: Solo es posible cambiar la forma de un array cuando aquella nueva forma que estemos aplicando sea soportada por el array. 
<br>
En el array original teniamos una matriz de 3 x 2 con 6 datos, si intentamos modificarlo a un array con menos o con mas elementos obtendremos un error de tipo `ValueError`

In [9]:
np.reshape(array, (6,6))

ValueError: cannot reshape array of size 6 into shape (6,6)

Al hacer un `reshape` a un array Numpy por default los ordena de forma líneal, un row tras de otro.
<br>
Tomemos como referencia el array en su forma original de 3 x 2  

In [ ]:
array = array.reshape(3,2)
array

array([[2, 6],
       [4, 8],
       [4, 2]])

Originalmente tenemos 3 rows, donde row 1 tiene [2, 6], row 2 tiene [4, 8] y el row 3 tiene [4, 2] si dejamos un solo row con 6 elementos entonces quedarian todos juntos empezando en 2 y terminando en el último 2

In [ ]:
array = np.reshape(array, (1,6))
array

array([[2, 6, 4, 8, 4, 2]])

Si ese mismo array lo cambiamos a una matriz de 2 filas con 3 columnas, entonces Numpy por default tomara los datos de 3 en 3 y los colocara en sus respectivas filas.

In [ ]:
array = np.reshape(array, (2, 3))
array

array([[2, 6, 4],
       [8, 4, 2]])

Una ventaja de hacer reshape con Numpy es que le podemos indicar el tipo de ordenamiento.

In [ ]:
# Ordenamiento como el lenguaje C
array = np.reshape(array, (3, 2), 'C')
array

array([[2, 6],
       [4, 8],
       [4, 2]])

In [ ]:
# Ordenamiento como el lenguaje fortran, En este caso el ordenamiento lo hace por columnas
array = np.reshape(array, (2, 3), 'F')
array

array([[2, 4, 8],
       [4, 6, 2]])

In [ ]:
# Ordenamiento optimizado segun el ordenador donde ejecutemos nuestro programa
array = np.reshape(array, (2, 3), 'A')
array

array([[2, 4, 8],
       [4, 6, 2]])

Utilizar el ordenamiento optimizado tiene la desventaja de que no sabremos como Numpy va a ordenar los datos de nuestro array, podemos establecer el ordenamiento que más nos convenga y aplicarlo con el fin de conocer como quedaran nuestros datos despues de ser ordenados con reshape.

---

### Practica

In [16]:
test_array = np.random.randint(0, 50, (3,3))
test_array

array([[46, 39, 48],
       [39, 44,  3],
       [ 3, 47, 32]])

In [17]:
test_array = test_array.reshape(-1)
test_array 

array([46, 39, 48, 39, 44,  3,  3, 47, 32])

In [21]:
test_array = np.reshape(test_array, (3,3) ,'F')
test_array

array([[46, 39,  3],
       [39, 44, 47],
       [48,  3, 32]])

In [22]:
test_array = np.reshape(test_array, (3,3) ,'A')
test_array

array([[46, 39,  3],
       [39, 44, 47],
       [48,  3, 32]])

In [25]:
tenso_test_array = np.random.randint(0, 20, (3, 4, 6))
tenso_test_array

array([[[18, 16, 16, 17, 15,  7],
        [ 6,  6,  6, 14, 16, 14],
        [ 6, 17,  0, 11,  9, 11],
        [ 6,  8, 11,  8,  4,  1]],

       [[17,  4,  7, 13,  5, 13],
        [18,  2,  7,  1, 12, 13],
        [13, 10,  1,  5,  2, 17],
        [11,  9, 15, 16, 12,  7]],

       [[13,  0, 10, 16, 13,  5],
        [14,  4,  4,  9,  9,  6],
        [14, 12, 11, 18, 18,  8],
        [ 8,  8,  9, 19,  8, 15]]])

In [29]:
tenso_test_array = np.reshape(tenso_test_array, -1)
tenso_test_array

array([18, 16, 16, 17, 15,  7,  6,  6,  6, 14, 16, 14,  6, 17,  0, 11,  9,
       11,  6,  8, 11,  8,  4,  1, 17,  4,  7, 13,  5, 13, 18,  2,  7,  1,
       12, 13, 13, 10,  1,  5,  2, 17, 11,  9, 15, 16, 12,  7, 13,  0, 10,
       16, 13,  5, 14,  4,  4,  9,  9,  6, 14, 12, 11, 18, 18,  8,  8,  8,
        9, 19,  8, 15])

In [30]:
tenso_test_array = np.reshape(tenso_test_array, (6, 12))
tenso_test_array

array([[18, 16, 16, 17, 15,  7,  6,  6,  6, 14, 16, 14],
       [ 6, 17,  0, 11,  9, 11,  6,  8, 11,  8,  4,  1],
       [17,  4,  7, 13,  5, 13, 18,  2,  7,  1, 12, 13],
       [13, 10,  1,  5,  2, 17, 11,  9, 15, 16, 12,  7],
       [13,  0, 10, 16, 13,  5, 14,  4,  4,  9,  9,  6],
       [14, 12, 11, 18, 18,  8,  8,  8,  9, 19,  8, 15]])

In [32]:
tenso_test_array = np.reshape(tenso_test_array, (6, 6, 2), 'F') # Re ordena los datos en base a su shape original (?)
tenso_test_array

array([[[18,  6],
        [16,  6],
        [16,  6],
        [17, 14],
        [15, 16],
        [ 7, 14]],

       [[ 6,  6],
        [17,  8],
        [ 0, 11],
        [11,  8],
        [ 9,  4],
        [11,  1]],

       [[17, 18],
        [ 4,  2],
        [ 7,  7],
        [13,  1],
        [ 5, 12],
        [13, 13]],

       [[13, 11],
        [10,  9],
        [ 1, 15],
        [ 5, 16],
        [ 2, 12],
        [17,  7]],

       [[13, 14],
        [ 0,  4],
        [10,  4],
        [16,  9],
        [13,  9],
        [ 5,  6]],

       [[14,  8],
        [12,  8],
        [11,  9],
        [18, 19],
        [18,  8],
        [ 8, 15]]])